[build]
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  # Setting Node.js version explicitly can prevent build tool compatibility errors
  NODE_VERSION = "20"
  
[functions]
  node_bundler = "esbuild"
